// @ts-nocheck

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({token}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          hello worlddddd
        </div>
        <h2> Token: {token}</h2>
       <button onClick={ ()=>{
        // Cookies.set("token", "ABCD", {expires:1/24})
        fetch("/api/login",{
          method: "post",
          headers:{
            "Content-Type": "application/json",
          },
          body: JSON.stringify({token:"ABCD"})
        })
       }}>

        set cookie

       </button>
       <button onClick={ ()=>{
        // Cookies.remove("token")
        fetch("/api/logout",{
          method: "post",
          headers:{
            "Content-Type": "application/json",
          },
          body: JSON.stringify({})
        })
       }}>

        remove cookie

       </button>
      </main>
    </>
  )
}

export function getServerSideProps({req, res}){
  // console.log(req.cookies.token)
  return {props:{token:req.cookies.token || ""}}
}